const PRIORITY_NORMAL = 1
const PRIORITY_IMPORTANT = 2
const PRIORITY_IMMEDIATELY = 3

export default {
  PRIORITY_NORMAL,
  PRIORITY_IMPORTANT,
  PRIORITY_IMMEDIATELY,
  DEFAULT_PRIORITY: PRIORITY_NORMAL
}