const STATUS_NEW = 1
const STATUS_IN_PROGRESS = 2
const STATUS_FINISHED = 3
const STATUS_CANCELLED = 4

export default {
  STATUS_NEW,
  STATUS_IN_PROGRESS,
  STATUS_FINISHED,
  STATUS_CANCELLED,
  DEFAULT_STATUS: STATUS_NEW
}